# Site
repository: alexb-green/alexb-green.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alex Green
title: Senior Measurement Innovation Executive
email: alexander.green@itv.com
website: https://alexb-green.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  alexb-green
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/aleximage.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Alex and I'm currently a Senior Measurement Innovation Executive at ITV. I have experience in Data Analysis, Implementation of Data Science technqiues,deployment and model building. Throughout my career I have shown enthusiasm, teamwork and diligence in everything I endeavour to accomplish.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ITV
        link: https://www.itvplc.com/
        # link_text: boringcompany.com
        sub_title: Senior Measurement Innovation Executive
        caption: March 2023 - present
        quote: >
            Easiest to see through the lens of the ITV behaviours where three behaviours in particular stand out. People find Alex to be a great collaborator; infectious with his enthusiasm and curiosity, someone who is full of energy and drive, taking the initiative and proactively offering help and support to others when needed.
        description: |
          My role focuses 

      - layout: left
        title: ITV
        link: https://www.itvplc.com/
        # link_text: boringcompany.com
        sub_title: Measurement Innovation Executive
        caption: March 2022 - March 2023
        quote: >
            Easiest to see through the lens of the ITV behaviours where three behaviours in particular stand out. People find Alex to be a great collaborator; infectious with his enthusiasm and curiosity, someone who is full of energy and drive, taking the initiative and proactively offering help and support to others when needed.
        description: |
          My role focuses 

      - layout: left
        title: ITV
        link: https://www.itvplc.com/
        # link_text: boringcompany.com
        sub_title: Data Science Apprentice
        caption: June 2021 - March 2022
        quote: >
            Easiest to see through the lens of the ITV behaviours where three behaviours in particular stand out. People find Alex to be a great collaborator; infectious with his enthusiasm and curiosity, someone who is full of energy and drive, taking the initiative and proactively offering help and support to others when needed.
        description: |
          My role focuses 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Westcliff High School for Girls
        caption: 2018-2020
        description: | # this will include new lines to allow paragraphs
          A Level Maths : A*
          A Level Further Maths : A
          A Level Physics : B
          A Level Chemistry : C

      - layout: left
        title: Eastwood Academy
        caption: 2013-2018
        description: | # this will include new lines to allow paragraphs
          GCSEs - 6 x A**(Grade 9s), 5 x A*(Grade 8s)



  - title: Technical Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Programming Languages: Highly advanced in Python, basic knowledge of R and Pyspark
      - Environments: Competent in both cloud infastructures like GCP and developer environments like VSCode
      
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Data Science some of my other interests and hobbies are:
      - Dancing: I have danced since I was young, and my passion is contemporary dance with elements of street and
                  modern. I have danced competitively and won the UK Janet Cram Awards (2012) and have danced in the
                  Royal Albert Hall and have been a finalist at the All-England UK Finals, UK Tap Awards and UK Ballet
                  Awards.
      - Film: I have a long-standing interest to cinema and films. In particular, sound design and cinematography

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag




 
