# Site
repository: alexb-green/alexb-green.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alex Green
title: 
email: alex.byron.green@gmail.com
website: https://alexb-green.github.io/
phone: 07926681674

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  alexb-green
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: alex-green-094867209
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
# url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/aleximage.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Alex and I’m currently a Senior Measurement Innovation Executive - Data Scientist at ITV. I have a strong foundation in data analytics, data science, statistical modelling and client consultation paired with advanced coding capabilities. I am driven by solving complex problems with enthusiasm, working diligently, and collaboratively to provide data-driven insights to business decisions and manage risk effectively. I am committed to continuous learning, and I have always striven to build upon my current skill set by embracing new challenges and delivering meaningful results.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ITV
        link: https://www.itvplc.com/
        # link_text: boringcompany.com
        sub_title: Senior Measurement Innovation Executive - Data Science
        caption: March 2023 - present
        quote: >
          People find Alex to be a great collaborator; infectious with his enthusiasm and curiosity, someone who is full of energy and drive, taking the initiative and proactively offering help and support to others when needed.
        description: |
         I assumed a more project governance function, managing more project tasks and project teams in implementing and integrating cloud-based data-driven solutions. Notable work examples include:
          - Developed a machine learning-based content clustering tool to segment users and products, enabling targeted strategies and optimising resource allocation.
          - Designed a regression-based research study to analyse the impact of time periods on web traffic, providing actionable insights to improve digital engagement strategies.
          - Led the analytical work for a new first-party dataset, implementing use cases to unlock revenue opportunities and enhance client reporting capabilities.
          - Executed experimental pilots for clients, applying power analysis to define control group sizes and conducting A/B tests to evaluate strategy effectiveness.


      - layout: left
        title: ITV
        link: https://www.itvplc.com/
        # link_text: boringcompany.com
        sub_title: Measurement Innovation Executive - Data Science
        caption: March 2022 - March 2023
        description: |
         My responsibilities increased to include the management of client relationships as well as the creation of new analytical tools for enhancing the analysis of marketing strategies and decisions. Notable work examples include: 
          - Carried out cross-domain analysis of advertising volumes and audience engagement, this was important in assessing risk for new services. 
          - Developed forecasting models based on regression analysis to forecast engagement metrics for content to support decision making and reduce risks. 
          - Helped in the creation of an automation tool for contextual targeting which enhanced the efficiency of advertising and also formed part of cost savings measures. 
          - Conducted experimental studies, using power analysis and synthetic control approach to assess the effects of marketing interventions to derive insights for the clients. 
          - Trained new team members, and standardized the onboarding process as well as the analysis approach within the team. 





      - layout: left
        title: ITV
        link: https://www.itvplc.com/
        # link_text: boringcompany.com
        sub_title: Data Science Apprentice
        caption: June 2021 - March 2022
        description: |
         I worked on enhancing the analytical skills, tools and processes to gauge the effectiveness of TV advertising on business results for the clients and incorporating the use of first-party data and third-party data providers. Notable work examples include:
          - Developed data pipelines that enabled me to collect, search and display first party data while improving the reporting processes and the efficiency of the operations.
          - Developed a dashboard to help compare the performance of the advertisers to that of the client’s benchmarks, to facilitate planning and competition strategies.
          - Worked with third party partners in measurement pilots, using statistics to evaluate the performance of the advertising approaches and the ROI.
          - Developed a NLP tool for the analysis of content and for the identification of the best audience segmentation in order to identify the best marketing strategies.


          
  - title: Technical Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Programming Languages: 
        - **Python (Expert)**: Proficient in libraries like pandas, scikit-learn; experience with building end-to-end machine learning pipelines.
        - **SQL (Expert)**: Advanced querying, optimisation, and database management (PostgreSQL, BigQuery).
        - **R (Intermediate)**: Data visualisation (ggplot2), data wrangling (tidyverse), and statistical modelling (tidymodels).
      - Cloud Platforms and Tools: Google Cloud Platform, AWS, Databricks, VSCode
      - Code Deployment : Github
      - ETL: Airflow
      - Data Analysis & Visualisation Tools: Excel (Intermediate), Looker Studio (Intermediate), Tableau (Basic).


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:


      - layout: left
        title: York St John University
        caption: September 2021- March 2025
        description: | # this will include new lines to allow paragraphs
          BSc (Honours) Data Science : 1st Class Honours (Predicted)

      - layout: left
        title: Westcliff High School for Girls
        caption: 2018-2020
        description: | # this will include new lines to allow paragraphs
          - A-Level Maths : A*
          - A-Level Further Maths : B 
          - A-Level Physics : B 
          - A-Level Chemistry : C 

      - layout: left
        title: Eastwood Academy
        caption: 2013-2018
        description: | # this will include new lines to allow paragraphs
          - GCSE: 3 x Grade A*
          - GCSE: 6 x Grade 9 (includes Mathematics)
          - GCSE: 2 x Grade 8 (includes English Language)


      
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data, some of my other interests and hobbies are:
      - Sports: I’m an avid runner and yoga enthusiast.
      - Film: I have a deep appreciation for cinema and attend a weekly film club.
      - Art: In my spare time I enjoy portraiture and life drawing.
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag




 
